FROM quay.io/toolbx-images/debian-toolbox:12

LABEL com.github.containers.toolbox="true" \
      name="debian-test-toolbox" \
      version="12" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Debian toolbox containers" \
      maintainer=""

COPY extra-packages /
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install $(cat extra-packages | xargs) && rm -rd /var/lib/apt/lists/*
RUN rm /extra-packages

