FROM quay.io/toolbx-images/debian-toolbox:12

LABEL com.github.containers.toolbox="true" \
      name="debian-test-toolbox" \
      version="12" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Debian toolbox containers" \
      maintainer=""

RUN gpg --keyserver keyserver.ubuntu.com --recv-key '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7'
RUN gpg --armor --export '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7' | tee /etc/apt/trusted.gpg.d/cran_debian_key.asc

COPY extra-sources /
RUN tee -a <extra-sources /etc/apt/sources.list

COPY extra-packages /
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install $(cat extra-packages | xargs) && rm -rd /var/lib/apt/lists/*
RUN rm /extra-packages /extra-sources

